[INFO] mkdir /mnt/btrndv1/opt/btrwin ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/bin ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/apps ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/subv ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/proton ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/wine ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/crossover ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/default ...
[INFO] cd /mnt/btrndv1/opt/btrwin/subv
[INFO] mkdir /mnt/btrndv1/opt/btrwin ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/bin ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/apps ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/subv ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/proton ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/wine ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/crossover ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/default ...
[INFO] cd /mnt/btrndv1/opt/btrwin/subv
[INFO] ln -s tpl_placeholder tpl_default
[INFO] ln -s default home-wine
[INFO] cd /mnt/btrndv1/opt/btrwin/default
[INFO] ln -s ../subv/default prefix
[INFO] ln -s ../loaders/wine/default wine
[INFO] ln -s ./loaders/proton/default proton
[INFO] ln -s ~/.wineuser user
[INFO] cd /home/hoefkens
[INFO] ln -s /mnt/btrndv1/opt/default/prefix .wine
[INFO] ln -s /mnt/btrndv1/opt/default/user .btrwinuser
[INFO] cd /opt
[INFO] ln -s /mnt/btrndv1/opt/btrwin btrwin
[INFO] mkdir /run/media/hoefkens/btrsdv1/opt/btrwin ...
[INFO] mkdir /run/media/hoefkens/btrsdv1/opt/btrwin/bin ...
[INFO] mkdir /run/media/hoefkens/btrsdv1/opt/btrwin/apps ...
[INFO] mkdir /run/media/hoefkens/btrsdv1/opt/btrwin/subv ...
[INFO] mkdir /run/media/hoefkens/btrsdv1/opt/btrwin/loaders ...
[INFO] mkdir /run/media/hoefkens/btrsdv1/opt/btrwin/loaders/proton ...
[INFO] mkdir /run/media/hoefkens/btrsdv1/opt/btrwin/loaders/wine ...
[INFO] mkdir /run/media/hoefkens/btrsdv1/opt/btrwin/loaders/crossover ...
[INFO] mkdir /run/media/hoefkens/btrsdv1/opt/btrwin/default ...
[INFO] cd /run/media/hoefkens/btrsdv1/opt/btrwin/subv
[INFO] ln -s tpl_placeholder tpl_default
[INFO] ln -s default home-wine
[INFO] cd /run/media/hoefkens/btrsdv1/opt/btrwin/default
[INFO] ln -s ../subv/default prefix
[INFO] ln -s ../loaders/wine/default wine
[INFO] ln -s ./loaders/proton/default proton
[INFO] ln -s ~/.wineuser user
[INFO] cd /home/hoefkens
[INFO] ln -s /run/media/hoefkens/btrsdv1/opt/default/prefix .wine
[INFO] ln -s /run/media/hoefkens/btrsdv1/opt/default/user .btrwinuser
[INFO] cd /opt
[INFO] ln -s /run/media/hoefkens/btrsdv1/opt/btrwin btrwin
[INFO] mkdir /mnt/btrndv1/opt/btrwin ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/bin ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/apps ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/subv ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/proton ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/wine ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/crossover ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/default ...
[INFO] cd /mnt/btrndv1/opt/btrwin/subv
[INFO] ln -s tpl_placeholder tpl_default
[INFO] ln -s default home-wine
[INFO] cd /mnt/btrndv1/opt/btrwin/default
[INFO] ln -s ../subv/default prefix
[INFO] ln -s ../loaders/wine/default wine
[INFO] ln -s ./loaders/proton/default proton
[INFO] ln -s ~/.wineuser user
[INFO] cd /home/hoefkens
[INFO] ln -s /mnt/btrndv1/opt/default/prefix .wine
[INFO] ln -s /mnt/btrndv1/opt/default/user .btrwinuser
[INFO] cd /opt
[INFO] ln -s /mnt/btrndv1/opt/btrwin btrwin
[INFO] mkdir /mnt/btrndv1/opt/btrwin ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/bin ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/apps ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/subv ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/proton ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/wine ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/crossover ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/default ...
[INFO] cd /mnt/btrndv1/opt/btrwin/subv
[INFO] ln -s tpl_placeholder tpl_default
[INFO] ln -s default home-wine
[INFO] cd /mnt/btrndv1/opt/btrwin/default
[INFO] ln -s ../subv/default prefix
[INFO] ln -s ../loaders/wine/default wine
[INFO] ln -s ./loaders/proton/default proton
[INFO] ln -s ~/.wineuser user
[INFO] cd /home/hoefkens
[INFO] ln -s /mnt/btrndv1/opt/default/prefix .wine
[INFO] ln -s /mnt/btrndv1/opt/default/user .btrwinuser
[INFO] cd /opt
[INFO] ln -s /mnt/btrndv1/opt/btrwin btrwin
[INFO] mkdir /mnt/btrndv1/opt/btrwin ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/bin ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/apps ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/subv ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/proton ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/wine ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/crossover ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/default ...
[INFO] cd /mnt/btrndv1/opt/btrwin/subv
[INFO] ln -s tpl_placeholder tpl_default
[INFO] ln -s default home-wine
[INFO] cd /mnt/btrndv1/opt/btrwin/default
[INFO] ln -s ../subv/default prefix
[INFO] ln -s ../loaders/wine/default wine
[INFO] ln -s ./loaders/proton/default proton
[INFO] ln -s ~/.wineuser user
[INFO] cd /home/hoefkens
[INFO] ln -s /mnt/btrndv1/opt/default/prefix .wine
[INFO] ln -s /mnt/btrndv1/opt/default/user .btrwinuser
[INFO] cd /opt
[INFO] ln -s /mnt/btrndv1/opt/btrwin btrwin
[INFO] mkdir /mnt/btrndv1/opt/btrwin ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/bin ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/apps ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/subv ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/proton ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/wine ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/crossover ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/default ...
[INFO] cd /mnt/btrndv1/opt/btrwin/subv
[INFO] ln -s tpl_placeholder tpl_default
[INFO] ln -s default home-wine
[INFO] cd /mnt/btrndv1/opt/btrwin/default
[INFO] ln -s ../subv/default prefix
[INFO] ln -s ../loaders/wine/default wine
[INFO] ln -s ./loaders/proton/default proton
[INFO] ln -s ~/.wineuser user
[INFO] cd /home/hoefkens
[INFO] ln -s /mnt/btrndv1/opt/default/prefix .wine
[INFO] ln -s /mnt/btrndv1/opt/default/user .btrwinuser
[INFO] cd /opt
[INFO] ln -s /mnt/btrndv1/opt/btrwin btrwin
[INFO] mkdir /mnt/btrndv1/opt/btrwin ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/bin ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/apps ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/subv ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/proton ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/wine ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/crossover ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/default ...
[INFO] cd /mnt/btrndv1/opt/btrwin/subv
[INFO] ln -s tpl_placeholder tpl_default
[INFO] ln -s default home-wine
[INFO] cd /mnt/btrndv1/opt/btrwin/default
[INFO] ln -s ../subv/default prefix
[INFO] ln -s ../loaders/wine/default wine
[INFO] ln -s ./loaders/proton/default proton
[INFO] ln -s ~/.wineuser user
[INFO] cd /home/hoefkens
[INFO] ln -s /mnt/btrndv1/opt/default/prefix .wine
[INFO] ln -s /mnt/btrndv1/opt/default/user .btrwinuser
[INFO] cd /opt
[INFO] ln -s /mnt/btrndv1/opt/btrwin btrwin
[INFO] mkdir /mnt/btrndv1/opt/btrwin ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/bin ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/apps ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/subv ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/proton ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/wine ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/crossover ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/default ...
[INFO] cd /mnt/btrndv1/opt/btrwin/subv
[INFO] ln -s tpl_placeholder tpl_default
[INFO] ln -s default home-wine
[INFO] cd /mnt/btrndv1/opt/btrwin/default
[INFO] ln -s ../subv/default prefix
[INFO] ln -s ../loaders/wine/default wine
[INFO] ln -s ./loaders/proton/default proton
[INFO] ln -s ~/.wineuser user
[INFO] cd /home/hoefkens
[INFO] ln -s /mnt/btrndv1/opt/default/prefix .wine
[INFO] ln -s /mnt/btrndv1/opt/default/user .btrwinuser
[INFO] cd /opt
[INFO] ln -s /mnt/btrndv1/opt/btrwin btrwin
[INFO] mkdir /mnt/btrndv1/opt/btrwin ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/bin ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/apps ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/subv ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/proton ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/wine ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/crossover ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/default ...
[INFO] cd /mnt/btrndv1/opt/btrwin/subv
[INFO] ln -s tpl_placeholder tpl_default
[INFO] ln -s default home-wine
[INFO] cd /mnt/btrndv1/opt/btrwin/default
[INFO] ln -s ../subv/default prefix
[INFO] ln -s ../loaders/wine/default wine
[INFO] ln -s ./loaders/proton/default proton
[INFO] ln -s ~/.wineuser user
[INFO] cd /home/hoefkens
[INFO] ln -s /mnt/btrndv1/opt/default/prefix .wine
[INFO] ln -s /mnt/btrndv1/opt/default/user .btrwinuser
[INFO] cd /opt
[INFO] ln -s /mnt/btrndv1/opt/btrwin btrwin
[INFO] mkdir /mnt/btrndv1/opt/btrwin ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/bin ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/apps ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/subv ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/proton ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/wine ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/crossover ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/default ...
[INFO] cd /mnt/btrndv1/opt/btrwin/subv
[INFO] ln -s tpl_placeholder tpl_default
[INFO] ln -s default home-wine
[INFO] cd /mnt/btrndv1/opt/btrwin/default
[INFO] ln -s ../subv/default prefix
[INFO] ln -s ../loaders/wine/default wine
[INFO] ln -s ./loaders/proton/default proton
[INFO] ln -s ~/.wineuser user
[INFO] cd /home/hoefkens
[INFO] ln -s /mnt/btrndv1/opt/default/prefix .wine
[INFO] ln -s /mnt/btrndv1/opt/default/user .btrwinuser
[INFO] cd /opt
[INFO] ln -s /mnt/btrndv1/opt/btrwin btrwin
[INFO] mkdir /mnt/btrndv1/opt/btrwin ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/bin ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/apps ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/subv ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/proton ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/wine ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/crossover ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/default ...
[INFO] cd /mnt/btrndv1/opt/btrwin/subv
[INFO] ln -s tpl_placeholder tpl_default
[INFO] ln -s default home-wine
[INFO] cd /mnt/btrndv1/opt/btrwin/default
[INFO] ln -s ../subv/default prefix
[INFO] ln -s ../loaders/wine/default wine
[INFO] ln -s ./loaders/proton/default proton
[INFO] ln -s ~/.wineuser user
[INFO] cd /home/hoefkens
[INFO] ln -s /mnt/btrndv1/opt/default/prefix .wine
[INFO] ln -s /mnt/btrndv1/opt/default/user .btrwinuser
[INFO] cd /opt
[INFO] ln -s /mnt/btrndv1/opt/btrwin btrwin
[INFO] mkdir /mnt/btrndv1/opt/btrwin ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/bin ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/apps ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/subv ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/proton ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/wine ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/crossover ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/default ...
[INFO] cd /mnt/btrndv1/opt/btrwin/subv
[INFO] ln -s tpl_placeholder tpl_default
[INFO] ln -s default home-wine
[INFO] cd /mnt/btrndv1/opt/btrwin/default
[INFO] ln -s ../subv/default prefix
[INFO] ln -s ../loaders/wine/default wine
[INFO] ln -s ./loaders/proton/default proton
[INFO] ln -s ~/.wineuser user
[INFO] cd /home/hoefkens
[INFO] ln -s /mnt/btrndv1/opt/default/prefix .wine
[INFO] ln -s /mnt/btrndv1/opt/default/user .btrwinuser
[INFO] cd /opt
[INFO] ln -s /mnt/btrndv1/opt/btrwin btrwin
[INFO] mkdir /mnt/btrndv1/opt/btrwin ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/bin ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/apps ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/subv ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/proton ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/wine ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/crossover ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/default ...
[INFO] cd /mnt/btrndv1/opt/btrwin/subv
[INFO] ln -s tpl_placeholder tpl_default
[INFO] ln -s default home-wine
[INFO] cd /mnt/btrndv1/opt/btrwin/default
[INFO] ln -s ../subv/default prefix
[INFO] ln -s ../loaders/wine/default wine
[INFO] ln -s ./loaders/proton/default proton
[INFO] ln -s ~/.wineuser user
[INFO] cd /home/hoefkens
[INFO] ln -s /mnt/btrndv1/opt/default/prefix .wine
[INFO] ln -s /mnt/btrndv1/opt/default/user .btrwinuser
[INFO] cd /opt
[INFO] ln -s /mnt/btrndv1/opt/btrwin btrwin
[INFO] mkdir /mnt/btrndv1/opt/btrwin ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/bin ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/apps ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/subv ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/proton ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/wine ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/crossover ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/default ...
[INFO] cd /mnt/btrndv1/opt/btrwin/subv
[INFO] ln -s tpl_placeholder tpl_default
[INFO] ln -s default home-wine
[INFO] cd /mnt/btrndv1/opt/btrwin/default
[INFO] ln -s ../subv/default prefix
[INFO] ln -s ../loaders/wine/default wine
[INFO] ln -s ./loaders/proton/default proton
[INFO] ln -s ~/.wineuser user
[INFO] cd /home/hoefkens
[INFO] ln -s /mnt/btrndv1/opt/default/prefix .wine
[INFO] ln -s /mnt/btrndv1/opt/default/user .btrwinuser
[INFO] cd /opt
[INFO] ln -s /mnt/btrndv1/opt/btrwin btrwin
[INFO] mkdir /mnt/btrndv1/opt/btrwin ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/bin ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/apps ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/subv ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/proton ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/wine ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/crossover ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/default ...
[INFO] cd /mnt/btrndv1/opt/btrwin/subv
[INFO] ln -s tpl_placeholder tpl_default
[INFO] ln -s default home-wine
[INFO] cd /mnt/btrndv1/opt/btrwin/default
[INFO] ln -s ../subv/default prefix
[INFO] ln -s ../loaders/wine/default wine
[INFO] ln -s ./loaders/proton/default proton
[INFO] ln -s ~/.wineuser user
[INFO] cd /home/hoefkens
[INFO] ln -s /mnt/btrndv1/opt/default/prefix .wine
[INFO] ln -s /mnt/btrndv1/opt/default/user .btrwinuser
[INFO] cd /opt
[INFO] ln -s /mnt/btrndv1/opt/btrwin btrwin
[INFO] mkdir /mnt/btrndv1/opt/btrwin ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/bin ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/apps ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/subv ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/proton ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/wine ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/crossover ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/default ...
[INFO] cd /mnt/btrndv1/opt/btrwin/subv
[INFO] ln -s tpl_placeholder tpl_default
[INFO] ln -s default home-wine
[INFO] cd /mnt/btrndv1/opt/btrwin/default
[INFO] ln -s ../subv/default prefix
[INFO] ln -s ../loaders/wine/default wine
[INFO] ln -s ./loaders/proton/default proton
[INFO] ln -s ~/.wineuser user
[INFO] cd /home/hoefkens
[INFO] ln -s /mnt/btrndv1/opt/default/prefix .wine
[INFO] ln -s /mnt/btrndv1/opt/default/user .btrwinuser
[INFO] cd /opt
[INFO] ln -s /mnt/btrndv1/opt/btrwin btrwin
[INFO] mkdir /mnt/btrndv1/opt/btrwin ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/bin ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/apps ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/subv ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/proton ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/wine ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/crossover ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/default ...
[INFO] cd /mnt/btrndv1/opt/btrwin/subv
[INFO] ln -s tpl_placeholder tpl_default
[INFO] ln -s default home-wine
[INFO] cd /mnt/btrndv1/opt/btrwin/default
[INFO] ln -s ../subv/default prefix
[INFO] ln -s ../loaders/wine/default wine
[INFO] ln -s ./loaders/proton/default proton
[INFO] ln -s ~/.wineuser user
[INFO] cd /home/hoefkens
[INFO] ln -s /mnt/btrndv1/opt/default/prefix .wine
[INFO] ln -s /mnt/btrndv1/opt/default/user .btrwinuser
[INFO] cd /opt
[INFO] ln -s /mnt/btrndv1/opt/btrwin btrwin
[INFO] mkdir /mnt/btrndv1/opt/btrwin ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/bin ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/apps ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/subv ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/proton ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/wine ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/crossover ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/default ...
[INFO] cd /mnt/btrndv1/opt/btrwin/subv
[INFO] ln -s tpl_placeholder tpl_default
[INFO] ln -s default home-wine
[INFO] cd /mnt/btrndv1/opt/btrwin/default
[INFO] ln -s ../subv/default prefix
[INFO] ln -s ../loaders/wine/default wine
[INFO] ln -s ./loaders/proton/default proton
[INFO] ln -s ~/.wineuser user
[INFO] cd /home/hoefkens
[INFO] ln -s /mnt/btrndv1/opt/default/prefix .wine
[INFO] ln -s /mnt/btrndv1/opt/default/user .btrwinuser
[INFO] cd /opt
[INFO] ln -s /mnt/btrndv1/opt/btrwin btrwin
[INFO] mkdir /mnt/btrndv1/opt/btrwin ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/bin ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/apps ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/subv ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/proton ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/wine ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/crossover ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/default ...
[INFO] cd /mnt/btrndv1/opt/btrwin/subv
[INFO] ln -s tpl_placeholder tpl_default
[INFO] ln -s default home-wine
[INFO] cd /mnt/btrndv1/opt/btrwin/default
[INFO] ln -s ../subv/default prefix
[INFO] ln -s ../loaders/wine/default wine
[INFO] ln -s ./loaders/proton/default proton
[INFO] ln -s ~/.wineuser user
[INFO] cd /home/hoefkens
[INFO] ln -s /mnt/btrndv1/opt/default/prefix .wine
[INFO] ln -s /mnt/btrndv1/opt/default/user .btrwinuser
[INFO] cd /opt
[INFO] ln -s /mnt/btrndv1/opt/btrwin btrwin
[INFO] mkdir /mnt/btrndv1/opt/btrwin ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/bin ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/apps ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/subv ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/proton ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/wine ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/crossover ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/default ...
[INFO] cd /mnt/btrndv1/opt/btrwin/subv
[INFO] ln -s tpl_placeholder tpl_default
[INFO] ln -s default home-wine
[INFO] cd /mnt/btrndv1/opt/btrwin/default
[INFO] ln -s ../subv/default prefix
[INFO] ln -s ../loaders/wine/default wine
[INFO] ln -s ./loaders/proton/default proton
[INFO] ln -s ~/.wineuser user
[INFO] cd /home/hoefkens
[INFO] ln -s /mnt/btrndv1/opt/default/prefix .wine
[INFO] ln -s /mnt/btrndv1/opt/default/user .btrwinuser
[INFO] cd /opt
[INFO] ln -s /mnt/btrndv1/opt/btrwin btrwin
[INFO] mkdir /mnt/btrndv1/opt/btrwin ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/bin ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/apps ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/subv ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/proton ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/wine ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/crossover ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/default ...
[INFO] cd /mnt/btrndv1/opt/btrwin/subv
[INFO] ln -s tpl_placeholder tpl_default
[INFO] ln -s default home-wine
[INFO] cd /mnt/btrndv1/opt/btrwin/default
[INFO] ln -s ../subv/default prefix
[INFO] ln -s ../loaders/wine/default wine
[INFO] ln -s ./loaders/proton/default proton
[INFO] ln -s ~/.wineuser user
[INFO] cd /home/hoefkens
[INFO] ln -s /mnt/btrndv1/opt/default/prefix .wine
[INFO] ln -s /mnt/btrndv1/opt/default/user .btrwinuser
[INFO] cd /opt
[INFO] ln -s /mnt/btrndv1/opt/btrwin btrwin
[INFO] mkdir /mnt/btrndv1/opt/btrwin ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/bin ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/apps ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/subv ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/proton ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/wine ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/crossover ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/default ...
[INFO] cd /mnt/btrndv1/opt/btrwin/subv
[INFO] ln -s tpl_placeholder tpl_default
[INFO] ln -s default home-wine
[INFO] cd /mnt/btrndv1/opt/btrwin/default
[INFO] ln -s ../subv/default prefix
[INFO] ln -s ../loaders/wine/default wine
[INFO] ln -s ./loaders/proton/default proton
[INFO] ln -s ~/.wineuser user
[INFO] cd /home/hoefkens
[INFO] ln -s /mnt/btrndv1/opt/default/prefix .wine
[INFO] ln -s /mnt/btrndv1/opt/default/user .btrwinuser
[INFO] cd /opt
[INFO] ln -s /mnt/btrndv1/opt/btrwin btrwin
[INFO] mkdir /mnt/btrndv1/opt/btrwin ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/bin ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/apps ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/subv ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/proton ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/wine ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/crossover ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/default ...
[INFO] cd /mnt/btrndv1/opt/btrwin/subv
[INFO] ln -s tpl_placeholder tpl_default
[INFO] ln -s default home-wine
[INFO] cd /mnt/btrndv1/opt/btrwin/default
[INFO] ln -s ../subv/default prefix
[INFO] ln -s ../loaders/wine/default wine
[INFO] ln -s ./loaders/proton/default proton
[INFO] ln -s ~/.wineuser user
[INFO] cd /home/hoefkens
[INFO] ln -s /mnt/btrndv1/opt/default/prefix .wine
[INFO] ln -s /mnt/btrndv1/opt/default/user .btrwinuser
[INFO] cd /opt
[INFO] ln -s /mnt/btrndv1/opt/btrwin btrwin
[INFO] mkdir /mnt/btrndv1/opt/btrwin ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/bin ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/apps ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/subv ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/proton ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/wine ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/crossover ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/default ...
[INFO] cd /mnt/btrndv1/opt/btrwin/subv
[INFO] ln -s tpl_placeholder tpl_default
[INFO] ln -s default home-wine
[INFO] cd /mnt/btrndv1/opt/btrwin/default
[INFO] ln -s ../subv/default prefix
[INFO] ln -s ../loaders/wine/default wine
[INFO] ln -s ./loaders/proton/default proton
[INFO] ln -s ~/.wineuser user
[INFO] cd /home/hoefkens
[INFO] ln -s /mnt/btrndv1/opt/default/prefix .wine
[INFO] ln -s /mnt/btrndv1/opt/default/user .btrwinuser
[INFO] cd /opt
[INFO] ln -s /mnt/btrndv1/opt/btrwin btrwin
[INFO] mkdir /mnt/btrndv1/opt/btrwin ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/bin ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/apps ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/subv ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/proton ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/wine ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/crossover ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/default ...
[INFO] cd /mnt/btrndv1/opt/btrwin/subv
[INFO] ln -s tpl_placeholder tpl_default
[INFO] ln -s default home-wine
[INFO] cd /mnt/btrndv1/opt/btrwin/default
[INFO] ln -s ../subv/default prefix
[INFO] ln -s ../loaders/wine/default wine
[INFO] ln -s ./loaders/proton/default proton
[INFO] ln -s ~/.wineuser user
[INFO] cd /home/hoefkens
[INFO] ln -s /mnt/btrndv1/opt/default/prefix .wine
[INFO] ln -s /mnt/btrndv1/opt/default/user .btrwinuser
[INFO] cd /opt
[INFO] ln -s /mnt/btrndv1/opt/btrwin btrwin
[INFO] mkdir /mnt/btrndv1/opt/btrwin ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/bin ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/apps ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/subv ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/proton ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/wine ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/crossover ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/default ...
[INFO] cd /mnt/btrndv1/opt/btrwin/subv
[INFO] ln -s tpl_placeholder tpl_default
[INFO] ln -s default home-wine
[INFO] cd /mnt/btrndv1/opt/btrwin/default
[INFO] ln -s ../subv/default prefix
[INFO] ln -s ../loaders/wine/default wine
[INFO] ln -s ./loaders/proton/default proton
[INFO] ln -s ~/.wineuser user
[INFO] cd /home/hoefkens
[INFO] ln -s /mnt/btrndv1/opt/default/prefix .wine
[INFO] ln -s /mnt/btrndv1/opt/default/user .btrwinuser
[INFO] cd /opt
[INFO] ln -s /mnt/btrndv1/opt/btrwin btrwin
[INFO] mkdir /mnt/btrndv1/opt/btrwin ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/bin ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/apps ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/subv ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/proton ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/wine ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/crossover ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/default ...
[INFO] cd /mnt/btrndv1/opt/btrwin/subv
[INFO] ln -s tpl_placeholder tpl_default
[INFO] ln -s default home-wine
[INFO] cd /mnt/btrndv1/opt/btrwin/default
[INFO] ln -s ../subv/default prefix
[INFO] ln -s ../loaders/wine/default wine
[INFO] ln -s ./loaders/proton/default proton
[INFO] ln -s ~/.wineuser user
[INFO] cd /home/hoefkens
[INFO] ln -s /mnt/btrndv1/opt/default/prefix .wine
[INFO] ln -s /mnt/btrndv1/opt/default/user .btrwinuser
[INFO] cd /opt
[INFO] ln -s /mnt/btrndv1/opt/btrwin btrwin
[INFO] mkdir /mnt/btrndv1/opt/btrwin ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/bin ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/apps ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/subv ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/proton ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/wine ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/crossover ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/default ...
[INFO] cd /mnt/btrndv1/opt/btrwin/subv
[INFO] ln -s tpl_placeholder tpl_default
[INFO] ln -s default home-wine
[INFO] cd /mnt/btrndv1/opt/btrwin/default
[INFO] ln -s ../subv/default prefix
[INFO] ln -s ../loaders/wine/default wine
[INFO] ln -s ./loaders/proton/default proton
[INFO] ln -s ~/.wineuser user
[INFO] cd /home/hoefkens
[INFO] ln -s /mnt/btrndv1/opt/btrwin/default/prefix .wine
[INFO] ln -s /mnt/btrndv1/opt/btrwin/default/user .btrwinuser
[INFO] cd /opt
[INFO] ln -s /mnt/btrndv1/opt/btrwin btrwin
[INFO] mkdir /mnt/btrndv1/opt/btrwin ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/bin ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/apps ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/subv ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/proton ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/wine ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/crossover ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/default ...
[INFO] cd /mnt/btrndv1/opt/btrwin/subv
[INFO] ln -s tpl_placeholder tpl_default
[INFO] ln -s default home-wine
[INFO] cd /mnt/btrndv1/opt/btrwin/default
[INFO] ln -s ../subv/default prefix
[INFO] ln -s ../loaders/wine/default wine
[INFO] ln -s ./loaders/proton/default proton
[INFO] ln -s ~/.wineuser user
[INFO] cd /home/hoefkens
[INFO] ln -s /mnt/btrndv1/opt/btrwin/default/prefix .wine
[INFO] ln -s /mnt/btrndv1/opt/btrwin/default/user .btrwinuser
[INFO] cd /opt
[INFO] ln -s /mnt/btrndv1/opt/btrwin btrwin
[INFO] mkdir /mnt/btrndv1/opt/btrwin ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/bin ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/apps ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/subv ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/proton ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/wine ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/loaders/crossover ...
[INFO] mkdir /mnt/btrndv1/opt/btrwin/default ...
[INFO] cd /mnt/btrndv1/opt/btrwin/subv
[INFO] ln -s tpl_placeholder tpl_default
[INFO] ln -s default home-wine
[INFO] cd /mnt/btrndv1/opt/btrwin/default
[INFO] ln -s ../subv/default prefix
[INFO] ln -s ../loaders/wine/default wine
[INFO] ln -s ./loaders/proton/default proton
[INFO] ln -s ~/.wineuser user
[INFO] cd /home/hoefkens
[INFO] ln -s /mnt/btrndv1/opt/btrwin/default/prefix .wine
[INFO] ln -s /mnt/btrndv1/opt/btrwin/default/user .btrwinuser
[INFO] cd /opt
[INFO] ln -s /mnt/btrndv1/opt/btrwin btrwin
